### PR TITLE
Reformatted request page footer and added nav bar links

### PR DESCRIPTION
**Pull request by hgwelliver**
Moved "Total Items: " and Request button to be above footer. 
Request page footer now matches main page footer.
Fixed page title to not overlap with nav bar.
Added links into nav bar to match main page.

### CODE REVIEW

**Comment by TreyDettmer** [comment]
On the current htmlcssteam branch the Admin_mainCatalog.html and mainCatalog.html files have been replaced by a single catalog.html file. I think if you delete your mainCatalog.html file and commit again, the conflict should be resolved.

**Comment by TreyDettmer** [comment]
also could you change the top nav bar links to match the ones on the catalog page. You should be able to replace it with
        <a id="upLogoLink" href="https://www.up.edu/index.html" target="_blank">
            
        </a>
        <a class="navBarLinks" href="#">Log In</a>
        <a class="navBarLinks" href="#"> Help</a>
        <a id="firstNavLink" class="navBarLinks" href="#"> Catalog</a>
        <a id="secondNavLink" class="navBarLinks" href="#"> View Requests</a>

**Comment by TreyDettmer** [comment]
whoops, this is what i meant to paste

`<a id="upLogoLink" href="https://www.up.edu/index.html" target="_blank">
            
        </a>
        
        <a class="navBarLinks" href="#">Log In</a>
        <a class="navBarLinks" href="#"> Help</a>
        <a id="firstNavLink" class="navBarLinks" href="#"> Catalog</a>
        <a id="secondNavLink" class="navBarLinks" href="#"> View Requests</a>`

**Comment by hgwelliver** [comment]
Modified the header and deleted mainCatalog.html. Looks like there are no conflicts now, but lmk if any more fixes are needed, I was having some git issues.

**Pull request merged**
